-- Run this file once in Supabase > SQL Editor.
create table if not exists public.buildings (
  id bigint generated by default as identity primary key,
  name text not null,
  address text not null,
  owner text not null default '',
  land_area numeric not null default 0,
  floor_area numeric not null default 0,
  approval_date date,
  note text not null default '',
  category text not null default 'corporate' check (category in ('personal','management','corporate')),
  lat double precision,
  lng double precision,
  is_public boolean not null default true,
  updated_at timestamptz not null default now(),
  updated_by uuid references auth.users(id)
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.buildings enable row level security;
alter table public.admin_users enable row level security;

revoke all on public.buildings from anon, authenticated;
grant select on public.buildings to anon, authenticated;
grant insert, update, delete on public.buildings to authenticated;
grant usage, select on sequence public.buildings_id_seq to authenticated;

create or replace function public.is_admin() returns boolean
language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.admin_users where user_id=auth.uid()) $$;

drop policy if exists "public reads published buildings" on public.buildings;
create policy "public reads published buildings" on public.buildings for select to anon, authenticated
using (is_public or public.is_admin());

drop policy if exists "admins insert buildings" on public.buildings;
create policy "admins insert buildings" on public.buildings for insert to authenticated with check (public.is_admin());
drop policy if exists "admins update buildings" on public.buildings;
create policy "admins update buildings" on public.buildings for update to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins delete buildings" on public.buildings;
create policy "admins delete buildings" on public.buildings for delete to authenticated using (public.is_admin());

drop policy if exists "admins can read admin list" on public.admin_users;
create policy "admins can read admin list" on public.admin_users for select to authenticated using (public.is_admin());

create or replace function public.set_building_audit() returns trigger language plpgsql security invoker as $$
begin new.updated_at=now();new.updated_by=auth.uid();return new;end $$;
drop trigger if exists buildings_audit on public.buildings;
create trigger buildings_audit before insert or update on public.buildings for each row execute function public.set_building_audit();

-- After creating the administrator in Authentication > Users, run:
-- insert into public.admin_users(user_id) select id from auth.users where email='YOUR_ADMIN_EMAIL';
